// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbqygmazfqvxwdckdisr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticXlnbWF6ZnF2eHdkY2tkaXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTIwMjcsImV4cCI6MjA2NDEyODAyN30.LXoFcTp7FdV9Mp3Gj_QXzHubQcpXu6AopQLBIou0m9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);